### ISSUE TITLE
rosrun Error: 3792764924

### ISSUE THREAD

**Issue by kaiiwoo** [basler/pylon-ros-camera#145] opened 2023-02-07 07:55 UTC
Hi, successfully built workspace, but I have an error when I run `rosrun pylon_camera pylon_camera_node`.

The original error message is below.

![image](https://user-images.githubusercontent.com/80252411/217185040-a0d344ec-71c0-4a1c-8459-c55097bc7bdc.png)

**Comment by FrancoisPicardDTI** [comment] 2023-02-21 10:54
Hello @kaiiwoo 
I am not managing to reproduce the error. Did you manage to solve it?
I would say that the error message is coming from `pylon_camera_base.hpp:`
```
template <typename CameraTrait>
bool PylonCameraImpl<CameraTrait>::grab(Pylon::CGrabResultPtr& grab_result)
```
Line 527: `ROS_ERROR_STREAM("Error: " << grab_result->GetErrorCode() << " " << grab_result->GetErrorDescription());`
Can you confirm that please?

Can you try as well to set a user id to the camera?

**Comment by FrancoisPicardDTI** [comment] 2023-03-08 13:20
I am closing the issue. Please reopen it if the problem is not solved on your side.

**Closed by FrancoisPicardDTI** 2023-03-08 13:20 UTC
