### ISSUE TITLE
Low frame rate and can't ptp sync

### ISSUE THREAD

**Issue by antun008** [basler/pylon-ros-camera#117] opened 2022-06-21 08:03 UTC
I'm struggling with ptp synchronization in the a2A1920-51gcPRO basler camera in pylon-ros-basler. Do you have ready-made solutions? Because I would like to connect the camera to the lidar and do their ptp synchronization.
Additionally, How could I get more FPS in rgb8 format? My camera supports 51 FPS, and the most I could get was 15 fps, and when it is further divided into three channels, I get 5 hz per rgb channel. I’m also sending you the configuration we’re using and we really don’t know what the problem is. Could you give us some optimal configuration, where we could get at least 30-40 FPS? We are using software triggering and I know that software trigger reduce fps to half, but maybe with beyond compression we could get more fps

I tried to change in the pylon application that my camera creates a GigE Compression Beyond photo, because in the pylon-ros-camera application on github I could not find the execution of that command. After that the camera even has that command turned on, but as long as I don't run roslaunch pylon_camera pylon_camera_node.launch, after that  command is turned off again. Obviously pylon and pylon-ros-camera are tearing each other apart. Why I’m writing about compression beyond at all, is because I’ve seen on your site that I can increase FPS that way.

For what purpouse I need use trigger_timeout and grab_timeout, and thus i need to change this (perhaps reduce or increase this paramteres).

Also, when i put mtu_size: 8192 into default.yaml file, it dosent change nothing, it stays 1500 as default
![image](https://user-images.githubusercontent.com/49721808/175038456-15e24b1a-0972-4ea2-ac54-a6682b96317d.png)

this is my yaml file:
device_user_id: ""
camera_info_url: file:///home/antek/programi/pylon/src/pylon-ros-camera/pylon_camera/config/ROS_19_6.yaml
image_encoding: "rgb8"
trigger_timeout: 800  # in ms !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
grab_timeout: 400  # in ms   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
grab_strategy : 0 #   !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
white_balance_auto : 1
exposure: 1000.0  #!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
frame_rate: 80
gige:
 mtu_size: 3000

Can I use hardware triggering in pylon-ros-camera, maybe with this I can increase FPS?

If it doesn't work that way, please, could you send me some instructions, just to get more FPS.
I've been struggling with this for days. I'm desperate already and I read all issue before on this repository!:(

**Comment by farhad-dalirani** [comment] 2022-06-22 19:05
use bayer rgb 8 instead of rgb. 
Also do this:
https://github.com/basler/pylon-ros-camera/issues/81

**Comment by farhad-dalirani** [comment] 2022-06-22 21:00
Also, look at this one:

https://stackoverflow.com/questions/72671393/problem-with-basler-camera-low-frame-rate-and-latency-ros/72721932#72721932

**Comment by antun008** [comment] 2022-06-23 10:19
But why also in mono8 format it gives me only a third of the predicted fps?
![image](https://user-images.githubusercontent.com/49721808/175276896-13971271-8fcb-41f1-a35d-5512122a6b97.png)

**Comment by antun008** [comment] 2022-06-23 10:47
> use bayer rgb 8 instead of rgb. Also do this: #81

I need just rgb8, not bayer

**Comment by antun008** [comment] 2022-06-24 06:55
And I finally found the way how to use compression beyond in ros, here is settings:
![image](https://user-images.githubusercontent.com/49721808/175479380-b096d600-4d72-442b-bd6c-7662c22300d7.png)

I managed to use compression to increase the fps to 27,356, but now the problem is that it doesn't want to show me any photo, I'm just getting this noise (you can see in picture above). Do you know maybe what the problem is?

Additionally, I tried using "enable_current_params_publisher" to increase fps as well, by putting "false", but nothing happened to me. It didn't use that changed parameter at all, because when I type "rostopic list" in this lower terminal  camera still Publish  /pylon_camera_node / currentParams:
![image](https://user-images.githubusercontent.com/49721808/175479990-6a0315d7-2c54-4871-9f95-0d227229c404.png)

**Comment by antun008** [comment] 2022-06-25 18:59
> In your launch file, you use UserSet1. Did you configure it inside the pylon viewer application and then did you upload you setting in UserSet1 memory on the camera?

Yes, I did it:)

**Comment by FrancoisPicardDTI** [comment] 2022-07-12 11:54
Hello

The ROS2 pylon driver v1.1.0 (branch _galactic_) gives now access through services to PTP related parameters and commands, allowing to enable PTP synchronization, to issue scheduled or not action commands, to use the periodic signal camera feature for ACE2 and the synchronous free-run feature for ACE1.
Hope it can help with this issue!

**Comment by demuma** [comment] 2022-07-13 10:19
As discussed in #81, go to your launch file and set "enable_current_params_publisher" to false. Don't ask why, but that should do the trick!

**Comment by FrancoisPicardDTI** [comment] 2022-10-31 13:18
I am closing the issue as it seems the issue is solved.

**Closed by FrancoisPicardDTI** 2022-10-31 13:18 UTC
